// Intentionally empty.
//
// Cloudflare Workers runtime types (D1Database, R2Bucket, Ai, Fetcher, etc.)
// are generated by `wrangler types` into worker-configuration.d.ts and exposed
// globally. This stub stands in for the real @cloudflare/workers-types package
// — which drizzle-orm references as an optional peer — so the two type sources
// do not collide.
