/**
 * @fileoverview Studio page — gallery of all spawned artifacts (PWAs, mind maps,
 * summary cards) served from R2 and indexed in D1.
 */
import React, { useState, useEffect } from "react";
import { Icon } from "../PressIcon";

interface Artifact {
  id: string;
  type: string;
  title: string;
  r2Key: string;
  workerUrl: string;
  prompt?: string | null;
  sourceArticleIds?: string | null;
  version?: number | null;
  createdAt?: string | null;
}

type TypeFilter = "all" | "pwa" | "mindmap" | "summary-card";

function typeIcon(type: string): string {
  switch (type) {
    case "pwa": return "layers";
    case "mindmap": return "zap";
    case "summary-card": return "stand";
    default: return "studio";
  }
}

function typeColor(type: string): string {
  switch (type) {
    case "pwa": return "oklch(0.65 0.18 250)";
    case "mindmap": return "oklch(0.72 0.16 150)";
    case "summary-card": return "oklch(0.7 0.15 35)";
    default: return "var(--muted-foreground)";
  }
}

export default function Studio() {
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [filter, setFilter] = useState<TypeFilter>("all");
  const [selected, setSelected] = useState<Artifact | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    const url = filter === "all" ? "/api/artifacts" : `/api/artifacts?type=${filter}`;
    fetch(url)
      .then((r) => r.json() as Promise<{ artifacts?: Artifact[] }>)
      .then((d) => {
        setArtifacts(d.artifacts ?? []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [filter]);

  if (selected) {
    return (
      <div className="art-viewer" style={{ position: "fixed", inset: 0, zIndex: 85, background: "var(--background)", display: "flex", flexDirection: "column" }}>
        <div className="art-vhead" style={{ display: "flex", alignItems: "center", gap: 11, padding: "12px 18px", borderBottom: "1px solid var(--border)" }}>
          <button className="btn" data-variant="ghost" data-size="sm" onClick={() => setSelected(null)}>
            <Icon name="chevronR" size={14} style={{ transform: "rotate(180deg)" }} /> Back
          </button>
          <span
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 5,
              fontSize: 11,
              fontWeight: 600,
              padding: "5px 9px",
              borderRadius: 6,
              background: `color-mix(in oklab, ${typeColor(selected.type)} 20%, transparent)`,
              color: typeColor(selected.type),
            }}
          >
            <Icon name={typeIcon(selected.type)} size={12} />
            {selected.type.toUpperCase()}
          </span>
          <span style={{ fontSize: 15, fontWeight: 600 }}>{selected.title}</span>
          <div style={{ flex: 1 }} />
          <a
            href={selected.workerUrl}
            target="_blank"
            rel="noopener"
            className="btn"
            data-variant="outline"
            data-size="sm"
          >
            <Icon name="ext" size={13} /> Open
          </a>
        </div>
        <div style={{ flex: 1, overflow: "hidden" }}>
          <iframe
            src={selected.workerUrl}
            style={{
              width: "100%",
              height: "100%",
              border: "none",
              background: "var(--surface)",
            }}
            title={selected.title}
          />
        </div>
      </div>
    );
  }

  return (
    <div className="page">
      <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: 16, marginBottom: 8 }}>
        <div>
          <h2 style={{ fontSize: 30, fontWeight: 700, fontFamily: "var(--font-editorial)", letterSpacing: "-.01em" }}>
            Studio
          </h2>
          <div style={{ color: "var(--muted-foreground)", fontSize: 13.5, marginTop: 8 }}>
            {artifacts.length} artifact{artifacts.length !== 1 ? "s" : ""} generated by agents
          </div>
        </div>
      </div>

      <div className="filterbar">
        {(["all", "pwa", "mindmap", "summary-card"] as TypeFilter[]).map((f) => (
          <button
            key={f}
            className={`chip ${filter === f ? "on" : ""}`}
            onClick={() => setFilter(f)}
          >
            {f === "all" ? "All" : f === "summary-card" ? "Cards" : f.charAt(0).toUpperCase() + f.slice(1) + "s"}
          </button>
        ))}
      </div>

      {loading ? (
        <div style={{ textAlign: "center", padding: 60, color: "var(--muted-foreground)" }}>
          <div style={{ fontSize: 14 }}>Loading…</div>
        </div>
      ) : artifacts.length === 0 ? (
        <div style={{ textAlign: "center", padding: 60, color: "var(--muted-foreground)" }}>
          <Icon name="studio" size={32} style={{ opacity: 0.3, marginBottom: 12 }} />
          <div style={{ fontSize: 14 }}>No artifacts yet. Ask the agent to generate one!</div>
        </div>
      ) : (
        <div className="studio-grid">
          {artifacts.map((a) => (
            <div key={a.id} className="studio-card" onClick={() => setSelected(a)}>
              <div className="studio-preview" style={{ display: "grid", placeItems: "center" }}>
                <Icon name={typeIcon(a.type)} size={36} style={{ color: typeColor(a.type), opacity: 0.6 }} />
                <span className="studio-type">
                  <Icon name={typeIcon(a.type)} size={10} />
                  {a.type}
                </span>
              </div>
              <div className="studio-meta">
                <div className="studio-title">{a.title}</div>
                <div className="studio-sub">
                  <Icon name="clock" size={11} />
                  {a.createdAt ? new Date(a.createdAt).toLocaleDateString() : "—"}
                  {a.version && a.version > 1 && (
                    <>
                      <span>·</span>
                      <span>v{a.version}</span>
                    </>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
