/**
 * @fileoverview Main Hono API router.
 *
 * Sets up the OpenAPI Hono application, middleware, and all routes. Bindings
 * are typed with the global `Env` generated by `wrangler types` — there is no
 * hand-maintained bindings interface.
 */

import { swaggerUI } from "@hono/swagger-ui";
import { OpenAPIHono, createRoute, z } from "@hono/zod-openapi";
import { apiReference } from "@scalar/hono-api-reference";
import { cors } from "hono/cors";
import { logger } from "hono/logger";

import { extractUrls } from "../ai/ingest/extractUrls";
import { ingestUrls } from "../ai/ingest/ingestUrls";
import { apiKeyMiddleware } from "./middleware/apiKey";
import { aiRouter } from "./routes/ai";
import { articlesRouter } from "./routes/articles";
import { artifactAssetsRouter, artifactsRouter } from "./routes/artifacts";
import { authRouter } from "./routes/auth";
import { dashboardRouter } from "./routes/dashboard";
import { documentsRouter } from "./routes/documents";
import { notificationsRouter } from "./routes/notifications";
import { tagsRouter } from "./routes/tags";
import { threadsRouter } from "./routes/threads";

/** Hono context variables set by middleware. */
export type Variables = {
  userId?: number;
  user?: {
    id: number;
    email: string;
    name: string;
  };
};

const app = new OpenAPIHono<{ Bindings: Env; Variables: Variables }>();

// Middleware
app.use("*", cors());
app.use("*", logger());

// Health check and standard endpoints
app.get("/api/ping", (c) => c.json({ status: "ok", timestamp: Date.now() }));
app.get("/context", (c) => c.json({ env: "production", version: "1.0.0" }));
app.get("/docs", (c) => c.text("API Documentation is available at /swagger or /scalar."));

/** Deep health check — verifies D1 connectivity. */
app.get("/health", async (c) => {
  const start = Date.now();
  let database: { status: string; responseTime: number; error?: string };
  try {
    await c.env.DB.prepare("SELECT 1").first();
    database = { status: "healthy", responseTime: Date.now() - start };
  } catch (err) {
    database = {
      status: "down",
      responseTime: Date.now() - start,
      error: err instanceof Error ? err.message : String(err),
    };
  }
  const healthy = database.status === "healthy";
  return c.json(
    {
      status: healthy ? "ok" : "degraded",
      services: { database },
      timestamp: new Date().toISOString(),
    },
    healthy ? 200 : 503,
  );
});

// OpenAPI generators
app.doc("/openapi.json", {
  openapi: "3.1.0",
  info: { version: "1.0.0", title: "News Archiver API" },
});
app.get("/swagger", swaggerUI({ url: "/openapi.json" }));
app.get("/scalar", apiReference({ spec: { url: "/openapi.json" } }));

// Ingestion API route. Browser Rendering + AI inference are expensive, so the
// endpoint requires the Secrets Store API key to prevent resource abuse.
app.use("/api/ingest", apiKeyMiddleware);

const ingestRoute = createRoute({
  method: "post",
  path: "/api/ingest",
  request: {
    body: {
      content: { "application/json": { schema: z.object({ urlsString: z.string() }) } },
    },
  },
  responses: {
    202: {
      content: { "application/json": { schema: z.object({ status: z.string() }) } },
      description: "Batch accepted for processing",
    },
  },
});

app.openapi(ingestRoute, (c) => {
  const { urlsString } = c.req.valid("json");
  const urls = extractUrls(urlsString);

  if (urls.length === 0) {
    return c.json({ status: "No valid URLs found" }, 202);
  }

  // Process asynchronously so the HTTP response is not blocked.
  c.executionCtx.waitUntil(
    ingestUrls(c.env, urls).then(
      () => {},
      (err) => console.error("Ingestion batch failed", err),
    ),
  );

  return c.json({ status: `Processing ${urls.length} URL(s)` }, 202);
});

// Mount routers
app.route("/api/auth", authRouter);
app.route("/api/dashboard", dashboardRouter);
app.route("/api/threads", threadsRouter);
app.route("/api/notifications", notificationsRouter);
app.route("/api/ai", aiRouter);
app.route("/api/documents", documentsRouter);
app.route("/api/articles", articlesRouter);
app.route("/api/tags", tagsRouter);
app.route("/api/artifacts", artifactsRouter);
app.route("/artifacts", artifactAssetsRouter);

export { app };
